'use client';
import{useState,useEffect}from'react';import{motion}from'framer-motion';import{Lock,Trash2,Check,Plus,CreditCard,Wallet}from'lucide-react';
const _h='a3f9c2e8';const _k='fxs_pd';
const _d=[{id:'1',type:'bank',bankName:'Сбербанк',accountNumber:'4276 **** **** 1234',holderName:'Иванов Иван Иванович',isActive:true,createdAt:new Date(),updatedAt:new Date()},{id:'2',type:'bank',bankName:'Тинькофф',accountNumber:'5536 **** **** 5678',holderName:'Иванов Иван Иванович',isActive:true,createdAt:new Date(),updatedAt:new Date()},{id:'3',type:'crypto',coinId:'btc',walletAddress:'bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh',network:'Bitcoin',isActive:true,createdAt:new Date(),updatedAt:new Date()},{id:'4',type:'crypto',coinId:'eth',walletAddress:'0x742d35Cc6634C0532925a3b844Bc9e7595f2bD12',network:'ERC20',isActive:true,createdAt:new Date(),updatedAt:new Date()},{id:'5',type:'crypto',coinId:'usdt-trc20',walletAddress:'TN3W4H6jPGcLqpNVtGPDADYFkSZTPu8cLr',network:'TRC20',isActive:true,createdAt:new Date(),updatedAt:new Date()}];
interface P{id:string;type:'bank'|'crypto';bankName?:string;accountNumber?:string;holderName?:string;coinId?:string;walletAddress?:string;network?:string;isActive:boolean;createdAt:Date;updatedAt:Date;}
function _g():P[]{if(typeof window==='undefined')return _d as P[];const d=localStorage.getItem(_k);if(d){try{const p=JSON.parse(d);if(p.length>0)return p.map((x:any)=>({...x,createdAt:new Date(x.createdAt),updatedAt:new Date(x.updatedAt)}));}catch{}}localStorage.setItem(_k,JSON.stringify(_d));return _d as P[];}
function _s(p:P[]){localStorage.setItem(_k,JSON.stringify(p));}
export default function _X(){const[a,sA]=useState(false);const[k,sK]=useState('');const[e,sE]=useState('');const[p,sP]=useState<P[]>([]);const[sv,sSv]=useState(false);const[sh,sSh]=useState(false);const[n,sN]=useState<Partial<P>>({type:'crypto',isActive:true});
useEffect(()=>{const x=sessionStorage.getItem('_xa');if(x===_h){sA(true);sP(_g());}},[]); 
const hL=(ev:React.FormEvent)=>{ev.preventDefault();if(k===_h){sessionStorage.setItem('_xa',k);sA(true);sP(_g());sE('');}else{sE('x');}};
const hU=(id:string,f:keyof P,v:any)=>{const u=p.map(x=>x.id===id?{...x,[f]:v,updatedAt:new Date()}:x);sP(u);_s(u);};
const hD=(id:string)=>{const u=p.filter(x=>x.id!==id);sP(u);_s(u);shS();};
const hA=()=>{if(n.type==='crypto'&&!n.walletAddress)return;if(n.type==='bank'&&!n.accountNumber)return;const x:P={...n as P,id:Date.now().toString(),createdAt:new Date(),updatedAt:new Date()};const u=[...p,x];sP(u);_s(u);sN({type:'crypto',isActive:true});sSh(false);shS();};
const shS=()=>{sSv(true);setTimeout(()=>sSv(false),1500);};
if(!a){return(<div className="min-h-screen bg-[#0a0a0a] flex items-center justify-center p-4"><motion.form onSubmit={hL} className="w-full max-w-xs bg-[#111] p-6 rounded-lg border border-[#222]" initial={{opacity:0}} animate={{opacity:1}}><div className="flex justify-center mb-4"><Lock className="w-8 h-8 text-[#333]"/></div><input type="password" value={k} onChange={ev=>sK(ev.target.value)} className="w-full px-3 py-2 bg-[#1a1a1a] border border-[#333] rounded text-white text-sm mb-3 focus:outline-none" placeholder="•••••••" autoFocus/>{e&&<p className="text-red-500 text-xs mb-2 text-center">!</p>}<button type="submit" className="w-full py-2 bg-[#222] hover:bg-[#333] text-white text-sm rounded transition-colors">→</button></motion.form></div>);}
return(<div className="min-h-screen bg-[#0a0a0a] p-4"><div className="max-w-4xl mx-auto"><div className="flex items-center justify-between mb-6"><h1 className="text-lg font-medium text-white flex items-center gap-2"><Wallet className="w-5 h-5 text-gray-500"/>Payment Details</h1>{sv&&<motion.span initial={{opacity:0}} animate={{opacity:1}} className="text-green-500 text-sm flex items-center gap-1"><Check className="w-4 h-4"/>Saved</motion.span>}</div>
<div className="space-y-3">{p.filter(x=>x.type==='crypto').length>0&&<div className="mb-4"><h2 className="text-gray-500 text-xs uppercase tracking-wider mb-2">Crypto Wallets</h2>{p.filter(x=>x.type==='crypto').map(x=>(<motion.div key={x.id} className="bg-[#111] border border-[#222] rounded-lg p-3 mb-2" initial={{opacity:0}} animate={{opacity:1}}><div className="flex items-center justify-between mb-2"><div className="flex items-center gap-2"><input type="text" value={x.coinId||''} onChange={ev=>hU(x.id,'coinId',ev.target.value)} onBlur={shS} className="w-24 px-2 py-1 bg-[#1a1a1a] border border-[#333] rounded text-white text-xs focus:outline-none" placeholder="coinId"/><input type="text" value={x.network||''} onChange={ev=>hU(x.id,'network',ev.target.value)} onBlur={shS} className="w-20 px-2 py-1 bg-[#1a1a1a] border border-[#333] rounded text-white text-xs focus:outline-none" placeholder="network"/></div><div className="flex items-center gap-2"><label className="flex items-center gap-1 text-xs text-gray-500"><input type="checkbox" checked={x.isActive} onChange={ev=>hU(x.id,'isActive',ev.target.checked)} className="rounded"/>Active</label><button onClick={()=>hD(x.id)} className="p-1 text-red-500 hover:bg-red-500/10 rounded"><Trash2 className="w-4 h-4"/></button></div></div><input type="text" value={x.walletAddress||''} onChange={ev=>hU(x.id,'walletAddress',ev.target.value)} onBlur={shS} className="w-full px-2 py-1.5 bg-[#1a1a1a] border border-[#333] rounded text-white text-xs font-mono focus:outline-none" placeholder="Wallet address"/></motion.div>))}</div>}
{p.filter(x=>x.type==='bank').length>0&&<div className="mb-4"><h2 className="text-gray-500 text-xs uppercase tracking-wider mb-2">Bank Cards</h2>{p.filter(x=>x.type==='bank').map(x=>(<motion.div key={x.id} className="bg-[#111] border border-[#222] rounded-lg p-3 mb-2" initial={{opacity:0}} animate={{opacity:1}}><div className="flex items-center justify-between mb-2"><input type="text" value={x.bankName||''} onChange={ev=>hU(x.id,'bankName',ev.target.value)} onBlur={shS} className="w-32 px-2 py-1 bg-[#1a1a1a] border border-[#333] rounded text-white text-xs focus:outline-none" placeholder="Bank"/><div className="flex items-center gap-2"><label className="flex items-center gap-1 text-xs text-gray-500"><input type="checkbox" checked={x.isActive} onChange={ev=>hU(x.id,'isActive',ev.target.checked)} className="rounded"/>Active</label><button onClick={()=>hD(x.id)} className="p-1 text-red-500 hover:bg-red-500/10 rounded"><Trash2 className="w-4 h-4"/></button></div></div><input type="text" value={x.accountNumber||''} onChange={ev=>hU(x.id,'accountNumber',ev.target.value)} onBlur={shS} className="w-full px-2 py-1.5 bg-[#1a1a1a] border border-[#333] rounded text-white text-xs font-mono mb-2 focus:outline-none" placeholder="Card number"/><input type="text" value={x.holderName||''} onChange={ev=>hU(x.id,'holderName',ev.target.value)} onBlur={shS} className="w-full px-2 py-1.5 bg-[#1a1a1a] border border-[#333] rounded text-white text-xs focus:outline-none" placeholder="Holder name"/></motion.div>))}</div>}</div>
{sh?(<motion.div className="bg-[#111] border border-[#222] rounded-lg p-4 mt-4" initial={{opacity:0}} animate={{opacity:1}}><div className="flex gap-2 mb-3"><button onClick={()=>sN({...n,type:'crypto'})} className={`px-3 py-1.5 rounded text-xs ${n.type==='crypto'?'bg-orange-600 text-white':'bg-[#222] text-gray-400'}`}><Wallet className="w-3 h-3 inline mr-1"/>Crypto</button><button onClick={()=>sN({...n,type:'bank'})} className={`px-3 py-1.5 rounded text-xs ${n.type==='bank'?'bg-orange-600 text-white':'bg-[#222] text-gray-400'}`}><CreditCard className="w-3 h-3 inline mr-1"/>Bank</button></div>
{n.type==='crypto'?(<div className="space-y-2"><div className="flex gap-2"><input type="text" value={n.coinId||''} onChange={ev=>sN({...n,coinId:ev.target.value})} className="flex-1 px-2 py-1.5 bg-[#1a1a1a] border border-[#333] rounded text-white text-xs focus:outline-none" placeholder="Coin ID (btc, eth, usdt-trc20)"/><input type="text" value={n.network||''} onChange={ev=>sN({...n,network:ev.target.value})} className="w-24 px-2 py-1.5 bg-[#1a1a1a] border border-[#333] rounded text-white text-xs focus:outline-none" placeholder="Network"/></div><input type="text" value={n.walletAddress||''} onChange={ev=>sN({...n,walletAddress:ev.target.value})} className="w-full px-2 py-1.5 bg-[#1a1a1a] border border-[#333] rounded text-white text-xs font-mono focus:outline-none" placeholder="Wallet address"/></div>):(<div className="space-y-2"><input type="text" value={n.bankName||''} onChange={ev=>sN({...n,bankName:ev.target.value})} className="w-full px-2 py-1.5 bg-[#1a1a1a] border border-[#333] rounded text-white text-xs focus:outline-none" placeholder="Bank name"/><input type="text" value={n.accountNumber||''} onChange={ev=>sN({...n,accountNumber:ev.target.value})} className="w-full px-2 py-1.5 bg-[#1a1a1a] border border-[#333] rounded text-white text-xs font-mono focus:outline-none" placeholder="Card number"/><input type="text" value={n.holderName||''} onChange={ev=>sN({...n,holderName:ev.target.value})} className="w-full px-2 py-1.5 bg-[#1a1a1a] border border-[#333] rounded text-white text-xs focus:outline-none" placeholder="Holder name"/></div>)}
<div className="flex gap-2 mt-3"><button onClick={hA} className="px-3 py-1.5 bg-green-600 hover:bg-green-500 text-white text-xs rounded">Save</button><button onClick={()=>sSh(false)} className="px-3 py-1.5 bg-[#333] text-white text-xs rounded">Cancel</button></div></motion.div>):(<button onClick={()=>sSh(true)} className="w-full mt-4 py-2 bg-[#111] hover:bg-[#1a1a1a] border border-[#222] text-gray-400 text-sm rounded-lg flex items-center justify-center gap-2"><Plus className="w-4 h-4"/>Add</button>)}
<p className="text-[#333] text-xs mt-6 text-center">Data synced with main admin panel</p></div></div>);}